title: Gaurav Kumar
logo: /assets/img/logo.png
description: He is a result-oriented professional with 7~ years of experience in design, development and maintenance projects on UiPath(RPA).
His professional experience includes Feasibility Analysis, Process Analysis, requirement walkthrough, Estimations, demonstration, defect resolution, and creative management support. He has  experience in working in Finance, Audit functions of Insurance, Banking, Retail, Telecom domains.
His experience includes development in C# .NET and leading  team in RPA UiPath. As an RPA developer, he has experience in developing automated solutions that work with different types of applications such as Microsoft Excel, Word, Outlook, SAP, Desktop, Citrix, Browser Based, PDF. He has worked on API provided by UiPath, Computer Vision and Abbyy Flexicapture.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
